### ISSUE TITLE
needs_update() unexpected behaviour

### ISSUE THREAD

**Issue by lsaffre** [mikeorr/Unipath#15]
Today I fell into a pitfall with unipath (the first time after
more than a year).  Here is an excerpt from some of my code::

    jarfile = outdir.child(n)
    libfile = LIBDIR.child(n)
    if libfile.needs_update([jarfile]):
        libfile.copy(jarfile)

In a first attempt I had written::

   if libfile.needs_update(jarfile):

which gave me a strange traceback::

    Traceback (most recent call last):
      ...
      File "/home/luc/hgwork/eid/fabfile.py", line 40, in sign_jars
        if libfile.needs_update(jarfile):
      File "/home/luc/pythonenvs/py27/local/lib/python2.7/site-packages/unipath/path.py", line 298, in needs_update
        if p.isdir():
    AttributeError: 'str' object has no attribute 'isdir'

Yes, the documentation clearly says that the argument to needs_update must be an iterable, and that Path objects behave like strings... and to avoid that pitfall, unipath would have to test on each whether it is a directory or not... so my suggestion is to just update the documentation to warn about this pitfall.

**Comment by mikeorr** [comment]
Fixed in c6ffa49.
