### ISSUE TITLE
> NameError: name 'unicode' is not defined 

### ISSUE THREAD

**Issue by gersande** [mikeorr/Unipath#16]
My colleague using Linux is not getting this error, but on OSX running `django-admin.py runserver` or `python manage.py shell` causes the command line to throw out this name error - we used unipath in our settings module. 

We're using Python 3 with virtual env with Unipath version 1.0. Any help would be super appreciated!

**Comment by mikeorr** [comment]
Fixed in 5f5dfdf. Keeping issue open until release.

The problem only occurs on platforms with Unicode filenames (`os.path.supports_unicode_filenames == True`). Linux apparently doesn't, so my tests always passed, and I had to put an "if True" to replicate the problem.

**Comment by gersande** [comment]
Good to hear. I have not had a chance to use Unipath in the last few months but may be using it again very soon so I'm happy to hear the commits are coming!

**Comment by mikeorr** [comment]
Fixed in 5f5df5f.

**Comment by njones11** [comment]
Any chance you could release a new tag with these fixes?

**Comment by mikeorr** [comment]
Released version 1.1 and tag 'v1.1'.
