### ISSUE TITLE
dump_path() not working

### ISSUE THREAD

**Issue by sesas** [mikeorr/Unipath#5]
```Python
from unipath import Path, tools

p = Path()
tools.dump_path(p)
```
Output:
```Python
Traceback (most recent call last):
  File "C:\Users\sesas\Documents\My Dropbox\Python Scripts\tests\unipath_test.py", line 5, in <module>
    tools.dump_path(p)
  File "C:\Python27\lib\site-packages\unipath\tools.py", line 28, in dump_path
    elif p.isdir():
TypeError: _isdir() takes exactly 1 argument (0 given)
```

**Comment by mikeorr** [comment]
I can't reproduce the first problem. Maybe it happens only on Windows.

Re the second problem, the behavior is correct. The path is the empty string, not related to anything in the filesystem. The parent of an empty path is an empty path. When you call `absolute`, it prefixes the current directory to the path. That's the point when the filesystem is consulted.  You should call `absolute` earlier if you want to use it like that.

**Comment by sesas** [comment]
Right, because the 'path' is different from the 'file system path'. I get
it now.  This way the idea of path can be manipulated without being tied to
a particular implementation. (or underlying OS)
